' Gambas module file

Public Function TestComprobacion(ruta As String) As String

  Dim vChk As String

  vChk = GitVersion(ruta)

  If Application.Version <> vChk Then
    Message.info(("New version found") & ": " & vchk)
  Else
    Message.info(("You have the same version as the one hosted on Github"))
  Endif

End

Public Function GitVersion(raw As String) As String

  Dim s As String
  Dim stx As String[]
  Dim r As String
  Dim v As String

  v = ""
  If Exist("/tmp/project.txt") Then
    Shell "rm /tmp/project.txt" Wait
  Endif

  Shell "wget -O '/tmp/project.txt' '" & raw & "'" Wait
  If Exist("/tmp/project.txt") Then
    s = File.Load("/tmp/project.txt")
    stx = Split(s, "\n")
    For Each r In stx
      If InStr(r, "Version=") Then
        If Split(r, "=")[0] = "Version" Then
          v = Split(r, "=")[1]
          Break
        Endif
      Endif
    Next
  Endif
  Return v

End
