' Gambas module file

Public Sub Copiar(listaficheros As String[], rutaorigen As String, rutadestino As String)

  Dim f As String
  Dim fnuevo As String

  For Each f In listaficheros
    If rutaorigen & "/" & f = rutadestino & "/" & f Then
      'es un fichero que ya exite
      fnuevo = File.BaseName(f) & " (copia)" & "." & File.Ext(f)
      Copy rutaorigen & "/" & f To rutadestino & "/" & fnuevo
    Else
      Copy rutaorigen & "/" & f To rutadestino & "/" & f

    Endif

  Next

End
